name: Semgrep

on:
  push:                    # Trigger on push events
  workflow_dispatch:       # Trigger manually via GitHub UI
  workflow_call:           # Triggered by other workflows
  pull_request:            # Trigger on pull requests

# Step 3: Define jobs: a set of steps that run together on a VM
jobs:
  semgrep_actions:          
    permissions:
      contents: read
      security-events: write
      actions: read
    name: Semgrep                
    runs-on: ubuntu-latest     
    container:
      image: returntocorp/semgrep       
    steps:
      - name: Checkout code
        uses: actions/checkout@v3         

      - name: Start scan
        run: semgrep scan --sarif --sarif-output=semgrep.sarif --error

      - name: Upload SARIF file to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
        if: always()
